### ISSUE TITLE
java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by 3arl0ck** [sqlcipher/sqlcipher-android-tests#21] opened 2017-08-04 06:47 UTC
at net.sqlcipher.database.SQLiteDatabase.dbopen (SQLiteDatabase.java)
  at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal (SQLiteDatabase.java)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase (SQLiteDatabase.java)
  at <OR>.openDatabase (SQLiteDatabase.java)
  at <OR>.openDatabase (SQLiteDatabase.java)
  at <OR>.openDatabase (SQLiteDatabase.java)
  at <OR>.openDatabase (SQLiteDatabase.java)
  at <OR>.openDatabase (SQLiteDatabase.java)
  at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase (SQLiteDatabase.java)
  at <OR>.openOrCreateDatabase (SQLiteDatabase.java)
  at <OR>.openOrCreateDatabase (SQLiteDatabase.java)
  at <OR>.openOrCreateDatabase (SQLiteDatabase.java)
  at <OR>.openOrCreateDatabase (SQLiteDatabase.java)
  at <OR>.openOrCreateDatabase (SQLiteDatabase.java)
  at <OR>.openOrCreateDatabase (SQLiteDatabase.java)
  at <OR>.openOrCreateDatabase (SQLiteDatabase.java)
  at <OR>.openOrCreateDatabase (SQLiteDatabase.java)
  at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java)
  at <OR>.getWritableDatabase (SQLiteOpenHelper.java)
  at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java)
  at <OR>.getWritableDatabase (SQLiteOpenHelper.java)
  at com.m.DatabaseHandler.checkDatabaseFromAssets (DatabaseHandler.java)
  at com.ml.DatabaseHandler.getWritableDatabase (DatabaseHandler.java)
  at com.ml.DatabaseHandler.getInstance (DatabaseHandler.java)
  at <OR>.getDatabase (DatabaseHandler.java)
  at com.r.reminders.AlarmReceiver.onReceive (AlarmReceiver.java)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3041)
  at android.app.ActivityThread.-wrap18 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1562)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6121)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:779)

**Comment by developernotes** [comment] 2017-08-07 14:16
Hi @3arl0ck 

Can you provide more information regarding the stack trace you posted? Do you receive this when attempting to run the test suite? What device/emulator creates this issue. An `UnsatisfiedLinkError` is typically due to not properly bundling SQLCipher for Android, in this case the native libraries may be missing from your final APK. This may be due to a project configuration issue, or an invalid ProGuard definition(s). Without any additional additional information, we will close this issue.

**Comment by BeanChan1987** [comment] 2017-08-25 06:30
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/TalpaCollect/Collect-debug.apk"],nativeLibraryDirectories=[/system/priv-app/TalpaCollect/lib/arm, /system/fake-libs, /system/priv-app/TalpaCollect/Collect-debug.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /system/lib, /vendor/lib, /system/vendor/lib]]] couldn't find "libsqlcipher.so"
                                                                                 at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                                 at java.lang.System.loadLibrary(System.java:1530)
                                                                                 at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:213)
                                                                                 at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:230)
                                                                                 at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:209)
                                                                                 at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:202)

**Comment by BeanChan1987** [comment] 2017-08-25 06:31
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/TalpaCollect/Collect-debug.apk"],nativeLibraryDirectories=[/system/priv-app/TalpaCollect/lib/arm, /system/fake-libs, /system/priv-app/TalpaCollect/Collect-debug.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /system/lib, /vendor/lib, /system/vendor/lib]]] couldn't find "libsqlcipher.so"
    at java.lang.Runtime.loadLibrary0(Runtime.java:972)
    at java.lang.System.loadLibrary(System.java:1530)
    at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:213)
    at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:230)
    at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:209)
    at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:202)

**Comment by sjlombardo** [comment] 2017-08-31 16:40
@BeanChan1987  This trace is showing that the application can't find the native library. However there isn't enough information to say why. You will need to provide additional details about how you are including SQLCipher for Android in your project, and what steps you have taken to troubleshoot thus far. Since this is not a bug with SQLCipher itself I am closing this ticket. I would recommend posting a topic on the SQLCipher discussion forum (https://discuss.zetetic.net/c/sqlcipher) with the aforementioned details for additional assistance.

**Closed by sjlombardo** 2017-08-31 16:40 UTC
