### ISSUE TITLE
SQLCipher crash when turn off the permission of call phone

### ISSUE THREAD

**Issue by Tiny1213** [sqlcipher/sqlcipher-android-tests#22] opened 2017-08-26 06:23 UTC
Expected Behavior

Actual Behavior

when I turn off the permission of call phone ，my App crash .
here is the log :
![image](https://user-images.githubusercontent.com/9071200/29739176-22d03f18-8a6a-11e7-831b-8fbf84eebd31.png)

App targetApi 22
Devices Android api 23+

Steps to Reproduce

1.install my App and run it
2.turn off the permission of call phone
3.run again
4.shut down
SQLCipher version (can be identified by executing PRAGMA cipher_version;):
3.5.4
SQLCipher for Android version:
3.5.4
Note: If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher discuss site. Thanks!

**Comment by developernotes** [comment] 2017-08-28 13:12
Hi @Tiny1213

This is a duplicate of your [original issue](https://github.com/sqlcipher/android-database-sqlcipher/issues/347) within the SQLCipher for Android project. If you have any additional details to share, please provide that [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/347).

**Closed by developernotes** 2017-08-28 13:12 UTC
